version: '2'
services:
    client:
        build: ./client/
        ports:
         - "3000:3000"
        volumes:
         - .:/client
        depends_on:
         - server
    server:
        build: .
        ports:
         - "8080:8080"
        volumes:
         - .:/server